### ISSUE TITLE
[bug] Plz help to remove the unused account from database

### ISSUE THREAD

**Issue by kerthcet** [cncf/devstats#5]
As displayed in the picture, my account is `kerthcet`, the `yaphetsglhf` is what I used before, how to remove it from the website. Thanks a lot.

The website link here is https://k8s.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=Last%20decade&var-metric=contributions&var-repogroup_name=All&var-repo_name=kubernetes%2Fkubernetes&var-country_name=China&var-companies=All

![image](https://user-images.githubusercontent.com/18364341/234828227-bb201159-23db-4263-947c-14a91fc745b5.png)

**Comment by lukaszgryglicki** [comment]
[This](https://github.com/cncf/gitdm/blob/master/FORBIDDEN_DATA.md) is how to remove data from the `cncf` `gitdm/devstats` stack.
I'll do it for you now.
Note that when I do it, it will take some time to import new data and make the current user disappear, let me know if this is urgent, in that case, I can go to the database and try to delete everything manually.

**Comment by lukaszgryglicki** [comment]
Also, let me know what exactly you need - remove both so they are no longer visible in DevStats, or just the new one/old one?
What exactly do you want to achieve?

**Comment by kerthcet** [comment]
Thanks, I want to keep the kerthcet and remove the yaphetsglhf.

This is not urgent, but hope to see the result before next Monday for data analysis, thanks a lot.

**Comment by kerthcet** [comment]
> [This](https://github.com/cncf/gitdm/blob/master/FORBIDDEN_DATA.md) is how to remove data from the cncf gitdm/devstats stack.

Thanks for the information.

**Comment by lukaszgryglicki** [comment]
Hmm, I wonder if this is ever possible - DevStats tracks data from archive files - each of them was saved at the time when it was created, so all past files will contain your past GitHub username - there is nothing that can be done with it.
I can add your old user to the "exclude list" so it won't show anywhere, but the new user contributions will only be visible and counted since that new user was created (so this user name was reported in archives).

Let me know now what you want me to do, I think there is no action item and we should keep both unless you want to `hide` old user contributions.

**Comment by kerthcet** [comment]
`Hide the old name yaphetsglhf and count the contributions for kerthcet since kerthcet was created`  looks good to me.

**Comment by lukaszgryglicki** [comment]
OK so on it now.
The old user will disappear when new affiliations are imported (which happens once per 4 weeks). If you need to remove it earlier let me know I will go to the database and manually remove that user references from all tables.

**Comment by kerthcet** [comment]
Thanks.

**Comment by lukaszgryglicki** [comment]
Done, also dropped from the DB - just in case you need it now.

**Comment by kerthcet** [comment]
Sorry for disturbing, but seems the problem still exists. kerthcet and yaphetsglhf(I want to remove) both exist.

<img width="1386" alt="image" src="https://github.com/cncf/devstats/assets/18364341/df4a14e1-7b81-4433-bdba-10ef3dd20e47">

**Comment by lukaszgryglicki** [comment]
I will take a look on Friday.

**Comment by lukaszgryglicki** [comment]
Checking this, I think I will have to add old name to the exclusion list, otherwise it will always show because that name appears in archive files that we are parsing, checkign what I can do now...

**Comment by lukaszgryglicki** [comment]
Data is now anonymized using your login sha `anon-sha1`. It cannot be removed, added support.
